### ISSUE TITLE
PHP 7.1 Support

### ISSUE THREAD

**Issue by deevus** [vim-php/phpctags#74]
phpctags doesn't like PHP 7.1 features

```
PHPParser: Syntax error, unexpected '?', expecting T_VARIABLE on line 207 - /path/to/file.php
```

**Comment by JoeThielen** [comment]
I get the same error message. 
Sample code:

```
public function getSomething(): ?string
{
    return $something;
}
```

**Comment by neurosnap** [comment]
Any update on this?

**Comment by JoeThielen** [comment]
I would love for this to get resolved.  I even tried to switch editors but ended up back with vim/gvim.  I tried Atom, which was neat, and has tons of plugins, but wow it's resource intensive.  Might have to sit down some time, wade through the code, and see if we can figure this one out the hard way...  I really miss the class browser which depends on this.

**Comment by Geraint** [comment]
It looks like #82 would fix this.

Any chance of someone taking a quick look, @vim-php ?

**Comment by jespinal** [comment]
Hello, dears:

Try cloning the repo locally, and changing around line 8 of the _**composer.json**_ file which which indicates which PHP-Parser to use (E.g. `"nikic/php-parser": "~4"`).

Issue a 

`$ composer update`

inside the repo directory, then you can do the normal:

`$ make all`

This which result in have the new **_phpctags.phar_** file created under the `build/` directory. I did it locally and it worked perfectly (it didn't complaint about PHP7.1+ things)

**Additional note:** in order to keep things fresh (and being able to update phpctags with composer), you might want to make a symbolic link from that phpctags.phar to somwhere in your path.

In my case, I have a `$HOME/bin` directory where I place things like these. I have it in my PATH (`export PATH=$PATH:$HOME/bin` in _**.bashrc**_). All I did was:

`$ ln -s $HOME/bin/phpctags_repo/build/phpctags.phar $HOME/bin/phpctags`

I tested it with a massive code base and it worked like a charm:

`$ phpctags --memory=-1 -R`

I hope this helps. Feel free to contact me if something was not clear.

**Comment by Geraint** [comment]
@jespinal I'm ashamed to admit I've only just got around to trying this, and it worked exactly as you described.  Thanks - much appreciated.

**Comment by jespinal** [comment]
I'm glad it was helpful, @Geraint

**Comment by Mte90** [comment]
I don't know if this one fixed it https://github.com/vim-php/phpctags/pull/82

**Comment by Geraint** [comment]
It looks like #82 did *not* fix it.

I've been working on a new machine and had just installed phpctags as instructed in the README, and have noticed that my tags are not getting generated for files that leverage PHP 7.1 features, like nullable return types.

I just tried the fix mentioned by @jespinal, and that worked again.

**Comment by Mte90** [comment]
So require an update of php-parser this project and generate a new phar.
I see that the project is like stalling/abandoned.
It is possible to bump this requirement? @gianarb

**Comment by InFog** [comment]
I'm working on this issue.

What I did until now: updated php version to 7.0+, php-parser to 4.5 and phpunit to 6.5.

This requires some extra work before the release, because phpunit changed the classes.

Expect a new release in the next few days.

**Comment by InFog** [comment]
Version 0.8.0 is released: https://github.com/vim-php/phpctags/releases/tag/0.8.0

PHP 7.0+ support is added.
Removed PHP 5.x support.
New `phpctags.phar` is already live on http://vim-php.com/phpctags/install/phpctags.phar
