### ISSUE TITLE
`make` doesn't work directly after cloning

### ISSUE THREAD

**Issue by cprn** [vim-php/phpctags#81]
Hi,
When I do:

    git clone repo_url
    make

I get the following error:

    make: *** No rule to make target 'composer.lock', needed by 'vendor'. Stop.

To solve it I removed `composer.lock` mentions from `Makefile` and it worked fine.

Do you want a PR with that change or do you think it'll cause problems in the future?

**Comment by jespinal** [comment]
Hello, @cprn : 

Try issuing a `$ composer update` before you issue the `$ make all` command. Also, you might want to change the PHP-Parser version from 3.X to 4 in the composer.json file in order to avoid PHP 7.1+ errors while generating your tags file.

Note: the new .phar file is generated under **_build/_** directory.

Regards,

**Comment by jespinal** [comment]
That's a good question. Maybe some team member from the project staff could provide further insights. There's possibly something we are not grasping.

**Comment by InFog** [comment]
This issue is fixed now. All the steps to install composer are in the `Makefile`.
